version: '3.3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/agile_deck_development"
      RAILS_ENV: development
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  bundle:
  node_modules:
